export const ADD_ANSWER = "ADD_ANSWER";
export const CHANGE_NEW_ANSWER_PROPERTIES = "CHANGE_NEW_ANSWER_PROPERTIES";
export const DELETE_ANSWER = "DELETE";
export const EDIT_ANSWER = "EDIT";
export const UPVOTE_ANSWER = "UPVOTE";
export const DOWNVOTE_ANSWER = "DOWNVOTE";