export const ADD_QUESTION = "ADD_QUESTION";
export const CHANGE_NEW_QUESTION_PROPERTIES = "CHANGE_NEW_QUESTION_PROPERTIES";
export const DELETE_QUESTION = "DELETE";
export const EDIT_QUESTION = "EDIT";
export const SEARCH_BY_TITLE = "SEARCH_BY_TITLE";
export const SEARCH_BY_TAG = "SEARCH_BY_TAG";
export const UPVOTE_QUESTION = "UPVOTE";
export const DOWNVOTE_QUESTION = "DOWNVOTE";